kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.23.17
  extraMounts:
  - hostPath: /etc/localtime
    containerPath: /etc/localtime
  - containerPath: /var/lib/kubelet/config.json
    hostPath: /root/.docker/config.json
  extraPortMappings:
  - containerPort: 30881
    hostPort: 9090
